In [1]:
import pandas as pd 
import numpy as np 

In [2]:
arr= np.array([12,14,10,44,32,19])
arr

array([12, 14, 10, 44, 32, 19])

In [4]:
arr.max()

44

In [5]:
arr.min()

10

In [6]:
arr.sum()

131

In [ ]:
arr.argmax() # index of maximum value

3

In [ ]:
arr.argmin() # index of minimum value

2

In [9]:
a1=np.array([
    [1,2,3],
    [5,4,3],
    [9,8,1]
])
a1

array([[1, 2, 3],
       [5, 4, 3],
       [9, 8, 1]])

In [10]:
a2=np.array([
    [11,2,6],
    [7,14,13],
    [8,18,11]
])
a2

array([[11,  2,  6],
       [ 7, 14, 13],
       [ 8, 18, 11]])

In [ ]:
a1+a2  #

array([[12,  4,  9],
       [12, 18, 16],
       [17, 26, 12]])

In [15]:
a1

array([[1, 2, 3],
       [5, 4, 3],
       [9, 8, 1]])

In [16]:
a1.sum(axis=1)

array([ 6, 12, 18])

In [17]:
a1.sum(axis=0)

array([15, 14,  7])

In [19]:
n=np.identity(6)

In [22]:
n

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
n.ndim

2

In [23]:
n.reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [25]:
n.reshape(2,18)

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1.]])

In [26]:
n.reshape(-1)

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1.])

In [27]:
i=np.identity(10)

In [29]:
i.reshape(4,25)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
np.sort(arr)

array([10, 12, 14, 19, 32, 44])